targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        generate_for:
          - lib/database/tables/**.dart
          - lib/database/daos/**.dart
          - lib/database/database.dart
        options:
          store_date_time_values_as_text: true
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules:
                - json1
                - fts5
                - rtree
          data_class_to_companions: true
          mutable_classes: false
          named_parameters: true
          named_parameters_always_required: true
          raw_result_set_data: false
          apply_converters_on_variables: true
          override_hash_and_equals_in_result_sets: true
          scoped_dart_components: true
          skip_verification_code: false
          use_column_name_as_json_key_when_defined_in_moor_file: true
          use_data_class_name_for_companions: true 